//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshu_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public int CTRY_ID { get; set; }
        public string CTRY_SORTNAME { get; set; }
        public string CRTY_NAME { get; set; }
        public Nullable<long> CTRY_PHONECODE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string CREA_BY { get; set; }
        public Nullable<System.DateTime> CREA_DATE { get; set; }
        public string UPDA_BY { get; set; }
        public Nullable<System.DateTime> UPDA_DATE { get; set; }
    }
}
