//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshu_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class devtestdbEntities : DbContext
    {
        public devtestdbEntities()
            : base("name=devtestdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COUNTRY> COUNTRies { get; set; }
        public virtual DbSet<SEND_EMAIL_BULK> SEND_EMAIL_BULK { get; set; }
    
        public virtual int INSERT_EMAILS(string hOST_EMAIL_ID, string hOST_PWD)
        {
            var hOST_EMAIL_IDParameter = hOST_EMAIL_ID != null ?
                new ObjectParameter("HOST_EMAIL_ID", hOST_EMAIL_ID) :
                new ObjectParameter("HOST_EMAIL_ID", typeof(string));
    
            var hOST_PWDParameter = hOST_PWD != null ?
                new ObjectParameter("HOST_PWD", hOST_PWD) :
                new ObjectParameter("HOST_PWD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_EMAILS", hOST_EMAIL_IDParameter, hOST_PWDParameter);
        }
    
        public virtual ObjectResult<RETRIEVE_EMAILS_Result> RETRIEVE_EMAILS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RETRIEVE_EMAILS_Result>("RETRIEVE_EMAILS");
        }
    
        public virtual int DELETE_EMAILS(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_EMAILS", iDParameter);
        }
    
        public virtual int UPDATE_EMAILS(string hOST_EMAIL_ID, string hOST_PWD, Nullable<int> iD)
        {
            var hOST_EMAIL_IDParameter = hOST_EMAIL_ID != null ?
                new ObjectParameter("HOST_EMAIL_ID", hOST_EMAIL_ID) :
                new ObjectParameter("HOST_EMAIL_ID", typeof(string));
    
            var hOST_PWDParameter = hOST_PWD != null ?
                new ObjectParameter("HOST_PWD", hOST_PWD) :
                new ObjectParameter("HOST_PWD", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_EMAILS", hOST_EMAIL_IDParameter, hOST_PWDParameter, iDParameter);
        }
    }
}
