//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshu_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEND_EMAIL_BULK
    {
        public int ID { get; set; }
        public string HOST_EMAIL_ID { get; set; }
        public string HOST_PWD { get; set; }
        public Nullable<int> SENT_COUNT { get; set; }
        public string SENT_STATUS { get; set; }
        public Nullable<System.DateTime> SENT_DATE { get; set; }
        public Nullable<int> SEB_STATUS { get; set; }
        public Nullable<System.DateTime> CREA_DATE { get; set; }
    }
}
